### PR TITLE
864 bytes

### PR DESCRIPTION
**Pull request by kamranayub**
- Removed redundant query for elements
- Don't even execute `yall` if no elements (removes need to unbind)

### CODE REVIEW

**Comment by malchata** [comment]
Just... wow.

**Comment by kamranayub** [comment]
HOLD

**Comment by malchata** [comment]
Hey, hang tight for a second, will ya?

**Comment by kamranayub** [comment]
dang you're too fast

**Comment by malchata** [comment]
No, you are.

**Comment by kamranayub** [comment]
I GOT EVEN MORE

**Comment by malchata** [comment]
Do what you need to, then PR again. I'll take a stab after that.

**Comment by kamranayub** [comment]
OK, last PR I think

**Pull request merged**
