### PR TITLE
831 bytes

### PR DESCRIPTION
**Pull request by kamranayub**
- Simplify binding function since no longer need to unbind

### CODE REVIEW

**Comment by kamranayub** [comment]
👍 I'm good now.

**Comment by malchata** [comment]
I've got some ideas. Let's see if I can take it further (if you didn't do them all already!)

**Comment by malchata** [comment]
Is there a reason we don't need to unbind? I'd like to avoid having a listener firing all the time, unless I'm just not reading this correctly.

**Comment by kamranayub** [comment]
Before, it was querying for all `.lazy` elements, then `yall` would execute and it would then see whether or not those elements were there. If not, it'd unbind. However, you'd still bind to the events regardless.

Now it just checks up front on DOMContentLoaded whether the elements exist so it bypasses the need to check on every `yall` invocation.

**Comment by kamranayub** [comment]
Ohhh, I see what you're getting at. After `yall` runs once and *removes* the lazy classes, it should unbind itself. Yeah, might need that still 👍

**Comment by malchata** [comment]
No worries. I still have some other tweaks that may yet work.

**Pull request merged**
