### PR TITLE
[WIP] reduce & improve...

### PR DESCRIPTION
**Pull request by leeoniya**
hey @malchata,

I felt like there was a lot of ceremony and huge dependencies to build such a tiny lib. i made a branch that guts and replaces basically all deps. i've removed eslint for now (it's pretty big). travis does nothing useful either all the tests are manual anyhow, so i dropped `http.js` since they can all be done by just opening the test file locally via `file:///`. also added a non-minified build. version stamping is done automatically by parsing `package.json` at build time. final output is smaller, too.

- replace Babel + Uglify -> Rollup + Buble + Terser
- remove Travis
- remove ESLint
- remove version from filename
- use dist builds in test/index.html
- auto-stamp version from package.json into banner
- remove http.js, just use file:/// for testing
- replace spread with es5 `for` loop to avoid need for Object.assign transpiling
- add lib name and version indentifier to dist builds

before/after:

yall-rollup-terser

feel free to close this if you feel it's not necessary (i won't be offended), though it'd be nice not to have to maintain my own fork.

feedback welcome :)

### CODE REVIEW

**Comment by leeoniya** [comment]
i have another branch continuing from this one that reduces the lib size (while hopefully retaining readability): https://github.com/leeoniya/yall.js/tree/codegolf

it also adds `{passive: true}` to event listeners.

**Comment by leeoniya** [comment]
ping @malchata

**Comment by malchata** [comment]
FYI: Closed this because I reworked the build process for yall, and incorporated some of these ideas around how the build process works.

**Comment by leeoniya** [comment]
@malchata great work on the recent size reductions! v2.3.0 is 💯 

i have a couple fully-updated iOS devices (iPhone SE, iPad 2 and an OSX Mojave VM) on hand and will try to add some data points to #46 sometime next week.

**Pull request closed without merging**
