### PR TITLE
Bugfix ie11 srcset

### PR DESCRIPTION
**Pull request by rkumorek**
Hey,

We've noticed recently on IE11 that line `element[dataAttr] = element.dataset[dataAttr]` sets `srcset` property on the element but it is not added as an attribute in DOM. This in turn doesn't allow us to use things like `picturefill`.

I can imagine the issue lies in IE11 not supporting srcset.

I am not sure if you're willing to go back to using `setAttribute` but to fully support IE11 I think it would be nice to be able to use `srcset`.

Thanks

### CODE REVIEW

**Comment by z3niths** [comment]
+1

**Comment by izharikov** [comment]
The same bug in Safari 9.1 (OS X El Capitan).

**Comment by malchata** [comment]
Hey, sorry for delay @rkumorek. Been juggling a few things over here as of late. 🤡

If you could rebase your work on top of what is currently in master, I can review and merge this change if it doesn't cause any issues.

**Comment by rkumorek** [comment]
Hey @malchata,

I have rebased my branch on top of master and I hope it is all correct (my first contribution).
Any issues I am happy to address.

Thanks

**Comment by malchata** [comment]
I need to tweak a few things post-merge, but this otherwise looks good!

**Pull request merged**
